dj_sponsoring/urls.py
# coding=utf-8

"""urls for the dj-sponsoring package."""


from django.urls import path

from . import views


app_name = 'dj_sponsoring'
urlpatterns = [
    path("",
         view=views.SponsorListView.as_view(),
         name='sponsors-list',
         ),
    path("create",
         view=views.SponsorCreateView.as_view(),
         name='sponsor-create',
         ),
    path("<int:pk>",
         view=views.SponsorDetailView.as_view(),
         name='sponsor-detail',
         ),
    path("<int:pk>/update",
         view=views.SponsorUpdateView.as_view(),
         name='sponsor-update',
         ),
    path("<int:pk>/delete",
         view=views.SponsorDeleteView.as_view(),
         name='sponsor-delete',
         ),
    path("<int:pk>/images",
         view=views.SponsorImageListView.as_view(),
         name='sponsor-images-list',
         ),
    path("<int:pk>/images/create",
         view=views.SponsorImageCreateView.as_view(),
         name='sponsor-image-create',
         ),
    path("<int:pk>/files",
         view=views.SponsorFileListView.as_view(),
         name='sponsor-files-list',
         ),
    path("<int:pk>/files/create",
         view=views.SponsorFileCreateView.as_view(),
         name='sponsor-file-create',
         ),
    path("images/<int:pk>",
         view=views.SponsorImageDetailView.as_view(),
         name='sponsor-image-detail',
         ),
    path("images/<int:pk>/update",
         view=views.SponsorImageUpdateView.as_view(),
         name='sponsor-image-update',
         ),
    path("images/<int:pk>/delete",
         view=views.SponsorImageDeleteView.as_view(),
         name='sponsor-image-delete',
         ),
    path("files/<int:pk>",
         view=views.SponsorFileDetailView.as_view(),
         name='sponsor-file-detail',
         ),
    path("files/<int:pk>/update",
         view=views.SponsorFileUpdateView.as_view(),
         name='sponsor-file-update',
         ),
    path("files/<int:pk>/delete",
         view=views.SponsorFileDeleteView.as_view(),
         name='sponsor-file-delete',
         ),
]

example/example/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path

urlpatterns = [
    path('login', auth_views.login, name="login"),
    path('logout', auth_views.logout, name="logout"),
    path('admin/', admin.site.urls, name='admin'),
    path('', include('dj_sponsoring.urls', namespace='dj-sponsoring')),
    path('markdownx/', include('markdownx.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dj_sponsoring/models.py
# coding=utf-8
"""."""

import os

from django.db import models
from django.utils.translation import ugettext_lazy as _

from markdownx.models import MarkdownxField
from markdownx.utils import markdownify

from .storage import OverwriteStorage


def sponsors_upload_to(instance, filename):
    """Callback to create the path where to store the files.

    If the file instance is a Sponsor, the file has to be the logo so it will be uploaded to
        MEDIA_ROOT/sponsors/<sponsor_name>/logo<ext>.
    If the file instance is a SponsorImage, the file has to be an image so it will be uploaded to
        MEDIA_ROOT/sponsors/<sponsor_name>/images/<filename>.
    If the file instance is a SponsorFile, the file has to be a file so it will be uploaded to
        MEDIA_ROOT/sponsors/<sponsor_name>/files/<filename>.
    """
    path = None
    if isinstance(instance, Sponsor):
        basename, ext = os.path.splitext(filename)
        path = os.path.join('sponsors', instance.name, 'logo{}'.format(ext))
    elif isinstance(instance, SponsorImage):
        path = os.path.join('sponsors', instance.sponsor.name, 'images', filename)
    elif isinstance(instance, SponsorFile):
        path = os.path.join('sponsors', instance.sponsor.name, 'files', filename)

    return path


class Sponsor(models.Model):
    """Sponsor entry class handler."""

    name = models.CharField(_('Sponsor name'), max_length=128)
    summary = models.CharField(_('Sponsor summary'), max_length=512)
    description = MarkdownxField(_('Sponsor description'))
    logo = models.ImageField(_('Sponsor logo'), storage=OverwriteStorage(), upload_to=sponsors_upload_to)
    url = models.URLField(_('Sponsor url'))
    created = models.DateTimeField('Sponsor creation date', auto_now_add=True)
    modified = models.DateTimeField('Sponsor last modification date', auto_now=True)

    def __str__(self):
        """Get name of the object."""
        return self.name

    class Meta:
        """Meta class."""

        verbose_name = _("sponsor")
        verbose_name_plural = _("sponsors")
        ordering = ("name", "-modified", "-created")

    def description_md(self):
        """Return the description text mardownified."""
        return markdownify(self.description)


class SponsorImage(models.Model):
    """Sponsor image class handler."""

    sponsor = models.ForeignKey('Sponsor', on_delete=models.CASCADE)
    img = models.ImageField(_('Sponsor image'), upload_to=sponsors_upload_to)
    alt = models.CharField(_('Sponsor image alternative text'), max_length=128)
    description = models.TextField(_('Sponsor image description text'), max_length=512, blank=True)
    created = models.DateTimeField('Sponsor image creation date', auto_now_add=True)
    modified = models.DateTimeField('Sponsor image last modification date', auto_now=True)

    def __str__(self):
        """Get name of the object."""
        return "{} - {}".format(self.sponsor.name, self.alt)

    class Meta:
        """Meta class."""

        verbose_name = _("sponsor image")
        verbose_name_plural = _("sponsor images")
        ordering = ("sponsor", "created")


class SponsorFile(models.Model):
    """Sponsor file class handler."""

    sponsor = models.ForeignKey('Sponsor', on_delete=models.CASCADE)
    file = models.FileField(_('Sponsor file'), upload_to=sponsors_upload_to)
    name = models.CharField(_('Sponsor file name'), max_length=128)
    description = models.CharField(_('Sponsor file small description'), max_length=128)
    created = models.DateTimeField('Sponsor file creation date', auto_now_add=True)
    modified = models.DateTimeField('Sponsor file last modification date', auto_now=True)

    def __str__(self):
        """Get name of the object."""
        return "{} - {}".format(self.sponsor.name, self.name)

    class Meta:
        """Meta class."""

        verbose_name = _("sponsor file")
        verbose_name_plural = _("sponsor files")
        ordering = ("sponsor", "name", "created")

dj_sponsoring/views.py
# coding=utf-8

"""Views."""

from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from .models import (
    Sponsor,
    SponsorFile,
    SponsorImage,
)


class SponsorListView(ListView):
    """View that returns the list of sponsors."""

    model = Sponsor
    paginate_by = 10


class SponsorDetailView(DetailView):
    """Show the details of a sponsor."""

    model = Sponsor


class SponsorCreateView(PermissionRequiredMixin, CreateView):
    """Create a sponsor."""

    model = Sponsor
    fields = '__all__'
    permission_required = 'dj_sponsoring.add_sponsor'

    def get_success_url(self):
        """Get the URL after the success."""
        return reverse('dj_sponsoring:sponsor-detail', kwargs={'pk': self.object.id})


class SponsorUpdateView(PermissionRequiredMixin, UpdateView):
    """Update a sponsor."""

    model = Sponsor
    fields = '__all__'
    permission_required = 'dj_sponsoring.change_sponsor'

    def get_success_url(self):
        """Get the URL after the success."""
        return reverse('dj_sponsoring:sponsor-detail', kwargs={'pk': self.object.id})


class SponsorDeleteView(PermissionRequiredMixin, DeleteView):
    """View that allows the deletion of a sponsor."""

    model = Sponsor
    permission_required = 'dj_sponsoring.delete_sponsor'

    def get_success_url(self, **kwargs):
        """Get the URL after the success."""
        return reverse('dj_sponsoring:sponsors-list')


class SponsorImageListView(ListView):
    """List the images."""

    model = SponsorImage
    paginate_by = 10

    def get_context_data(self, **kwargs):
        """."""
        context = super().get_context_data(**kwargs)
        context['sponsor'] = Sponsor.objects.get(id=self.kwargs['pk'])
        return context

    def get_queryset(self, *args, **kwargs):
        """."""
        qs = SponsorImage.objects.all()
        if 'pk' in self.kwargs:
            qs = SponsorImage.objects.filter(sponsor__id=self.kwargs['pk'])
        return qs


class SponsorImageDetailView(DetailView):
    """Show the detail of an image."""

    model = SponsorImage

    def get_context_data(self, **kwargs):
        """."""
        context = super().get_context_data(**kwargs)
        return context


class SponsorImageCreateView(PermissionRequiredMixin, CreateView):
    """SponsorImageCreateView."""

    model = SponsorImage
    fields = ['alt', 'description', 'img']
    permission_required = 'dj_sponsoring.add_sponsorimage'

    def get_context_data(self, **kwargs):
        """."""
        context = super().get_context_data(**kwargs)
        context['sponsor'] = Sponsor.objects.get(id=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        """Validate the form."""
        form.instance.sponsor = Sponsor.objects.get(id=self.kwargs['pk'])
        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        """Get the URL after the success."""
        return reverse('dj_sponsoring:sponsor-image-detail', kwargs={'pk': self.object.id})


class SponsorImageUpdateView(PermissionRequiredMixin, UpdateView):
    """SponsorImageUpdateView."""

    model = SponsorImage
    fields = ['alt', 'description', 'img']
    permission_required = 'dj_sponsoring.change_sponsorimage'

    def form_valid(self, form):
        """Validate the form."""
        form.instance.sponsor = Sponsor.objects.get(id=self.kwargs['pk'])
        return super().form_valid(form)

    def get_success_url(self):
        """Get the URL after the success."""
        return reverse('dj_sponsoring:sponsor-image-detail', kwargs={'pk': self.object.id})


class SponsorImageDeleteView(PermissionRequiredMixin, DeleteView):
    """SponsorImageDeleteView."""

    model = SponsorImage
    permission_required = 'dj_sponsoring.delete_sponsorimage'

    def get_success_url(self):
        """Get the URL after the success."""
        return reverse('dj_sponsoring:sponsor-images-list', kwargs={'pk': self.kwargs['pk']})


class SponsorFileListView(ListView):
    """SponsorFileListView."""

    model = SponsorFile
    paginate_by = 10

    def get_context_data(self, **kwargs):
        """."""
        context = super().get_context_data(**kwargs)
        context['sponsor'] = Sponsor.objects.get(id=self.kwargs['pk'])
        return context

    def get_queryset(self, *args, **kwargs):
        """."""
        qs = SponsorFile.objects.all()
        if 'pk' in self.kwargs:
            qs = SponsorFile.objects.filter(sponsor__id=self.kwargs['pk'])
        return qs


class SponsorFileDetailView(DetailView):
    """SponsorFileDetailView."""

    model = SponsorFile


class SponsorFileCreateView(PermissionRequiredMixin, CreateView):
    """SponsorFileCreateView."""

    model = SponsorFile
    fields = ['name', 'description', 'file']
    permission_required = 'dj_sponsoring.add_sponsorfile'

    def get_context_data(self, **kwargs):
        """."""
        context = super().get_context_data(**kwargs)
        context['sponsor'] = Sponsor.objects.get(id=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        """Validate the form."""
        form.instance.sponsor = Sponsor.objects.get(id=self.kwargs['pk'])
        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        """Get the URL after the success."""
        return reverse('dj_sponsoring:sponsor-file-detail', kwargs={'pk': self.object.id})


class SponsorFileUpdateView(PermissionRequiredMixin, UpdateView):
    """SponsorFileUpdateView."""

    model = SponsorFile
    fields = ['name', 'description', 'file']
    permission_required = 'dj_sponsoring.change_sponsorfile'

    def get_success_url(self):
        """Get the URL after the success."""
        return reverse('dj_sponsoring:sponsor-file-detail', kwargs={'pk': self.object.id})


class SponsorFileDeleteView(PermissionRequiredMixin, DeleteView):
    """SponsorFileDeleteView."""

    model = SponsorFile
    permission_required = 'dj_sponsoring.delete_sponsorfile'

    def get_success_url(self):
        """Get the URL after the success."""
        return reverse('dj_sponsoring:sponsor-files-list', kwargs={'pk': self.kwargs['pk']})

dj_sponsoring/templates/dj_sponsoring/base.html
{% comment %}
As the developer of this package, don't place anything here if you can help it
since this allows developers to have interoperability between your template
structure and their own.

Example: Developer melding the 2SoD pattern to fit inside with another pattern::

    {% extends "base.html" %}
    {% load static %}

    <!-- Their site uses old school block layout -->
    {% block extra_js %}

        <!-- Your package using 2SoD block layout -->
        {% block javascript %}
            <script src="{% static 'js/ninja.js' %}" type="text/javascript"></script>
        {% endblock javascript %}

    {% endblock extra_js %}
{% endcomment %}

dj_sponsoring/templates/dj_sponsoring/sponsor_confirm_delete.html
<h1 class="float-left">{{ sponsor }}</h1>

<form method="post">
    {% csrf_token %}
    <p>Do you really want to delete that sponsor and everything linked to it?</p>
    <button class="btn btn-primary btn-sm" type="submit">Confirm</button>
</form>

dj_sponsoring/templates/dj_sponsoring/sponsor_detail.html
<h1 class="float-left">{{ sponsor }}</h1>

{% if sponsor.logo %}
  <div class="col-1 float-left">
    <img class="d-block w-100" src="{{ sponsor.logo.url }}" alt="{{ sponsor.name }}'s logo">
  </div>
  <div class="col-11 float-right">
    <p>{{ sponsor.summary }}</p>
    <p>{{ sponsor.description_md|safe }}</p>
  <div>
{% else %}
  <p>{{ sponsor.summary }}</p>
  <p>{{ sponsor.description_md|safe }}</p>
{% endif %}

dj_sponsoring/templates/dj_sponsoring/sponsor_form.html
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  {{ form.media }}
  <button class="btn btn-primary btn-sm" type="submit">Save</button>
</form>

dj_sponsoring/templates/dj_sponsoring/sponsor_list.html
{% for s in sponsor_list %}
  {% if forloop.first %}
    <ul>
  {% endif %}

  <li>{{ s }}</li>

  {% if forloop.last %}
    </ul>
  {% endif %}
{% empty %}
  <p>No sponsors...</p>
  <p>You can create one <a href="{% url 'dj_sponsoring:sponsor-create' %}">here</a></p>
{% endfor %}

dj_sponsoring/templates/dj_sponsoring/sponsordocument_confirm_delete.html
<h1 class="float-left">{{ object }}</h1>

<form method="post">
  {% csrf_token %}
  <p>Do you really want to delete that document?</p>
  <button class="btn btn-primary btn-sm" type="submit">Confirm</button>
</form>

dj_sponsoring/templates/dj_sponsoring/sponsordocument_form.html
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button class="btn btn-primary btn-sm" type="submit">Save</button>
</form>

dj_sponsoring/templates/dj_sponsoring/sponsorfile_confirm_delete.html
<h1 class="float-left">{{ sponsorfile }}</h1>

<form method="post">
  {% csrf_token %}
  <p>Do you really want to delete that file?</p>
  <button class="btn btn-primary btn-sm" type="submit">Confirm</button>
</form>

dj_sponsoring/templates/dj_sponsoring/sponsorfile_detail.html
<h1>{{ sponsorfile }}</h1>

<p>Name: {{ sponsorfile.name }}</p>
<p>Description: {{ sponsorfile.description }}</p>

{% if sponsorfile.file %}
  <a href="{{ sponsorfile.file.url }}">Link</a>
{% endif %}

dj_sponsoring/templates/dj_sponsoring/sponsorfile_list.html
{% for d in sponsorfile_list %}
  {% if forloop.first %}
    <ul>
  {% endif %}

  <li>
      <a href="{% url 'dj_sponsoring:sponsor-file-detail' d.id %}">{{ d.name }}</a>
  </li>

  {% if forloop.last %}
    </ul>
  {% endif %}
{% empty %}
  <p>No files for this sponsor...</p>
  <p>You can create one <a href="{% url 'dj_sponsoring:sponsor-file-create' sponsor.id %}">here</a></p>
{% endfor %}

dj_sponsoring/templates/dj_sponsoring/sponsorimage_confirm_delete.html
<h1 class="float-left">{{ sponsorimage }}</h1>

<form method="post">
  {% csrf_token %}
  <p>Do you really want to delete that image?</p>
  <button class="btn btn-primary btn-sm" type="submit">Confirm</button>
</form>

<img class="d-block w-100" src="{{ sponsorimage.img.url }}" alt="{{ sponsorimage.alt }}">

dj_sponsoring/templates/dj_sponsoring/sponsorimage_detail.html
<h1>{{ sponsorimage }}</h1>

{% if sponsorimage.img %}
  <img class="d-block w-100" src="{{ sponsorimage.img.url }}" alt="{{ sponsorimage.alt }}">
{% endif %}

<p>Alternative text: {{ sponsorimage.alt }}</p>
<p>Description: {{ sponsorimage.description }}</p>

dj_sponsoring/templates/dj_sponsoring/sponsorimage_form.html
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  {{ form.media }}
  <button class="btn btn-primary btn-sm" type="submit">Save</button>
</form>

dj_sponsoring/templates/dj_sponsoring/sponsorimage_list.html
{% for i in sponsorimage_list %}
  {% if forloop.first %}
    <ul>
  {% endif %}

  <li>
      <a href="{% url 'dj_sponsoring:sponsor-image-detail' i.id %}">{{ i }}</a>
      <p>{{ i.description }}</p>
      {% if i.img %}
        <img src="{{ i.img.url }}" alt="{{ i.alt }}">
      {% endif %}
    </a>
  </li>

  {% if forloop.last %}
    </ul>
  {% endif %}
{% empty %}
  <p>No images for this sponsor...</p>
  <p>You can create one <a href="{% url 'dj_sponsoring:sponsor-image-create' sponsor.id %}">here</a></p>
{% endfor %}