dj_sponsoring/urls.py
# coding=utf-8

"""urls for the dj-sponsoring package."""


from django.urls import path

from . import views


app_name = 'dj_sponsoring'
urlpatterns = [
    path("",
         view=views.SponsorListView.as_view(),
         name='sponsors-list',
         ),
    path("create",
         view=views.SponsorCreateView.as_view(),
         name='sponsor-create',
         ),
    path("<int:pk>",
         view=views.SponsorDetailView.as_view(),
         name='sponsor-detail',
         ),
    path("<int:pk>/update",
         view=views.SponsorUpdateView.as_view(),
         name='sponsor-update',
         ),
    path("<int:pk>/delete",
         view=views.SponsorDeleteView.as_view(),
         name='sponsor-delete',
         ),
    path("<int:pk>/images",
         view=views.SponsorImageListView.as_view(),
         name='sponsor-images-list',
         ),
    path("<int:pk>/images/create",
         view=views.SponsorImageCreateView.as_view(),
         name='sponsor-image-create',
         ),
    path("<int:pk>/files",
         view=views.SponsorFileListView.as_view(),
         name='sponsor-files-list',
         ),
    path("<int:pk>/files/create",
         view=views.SponsorFileCreateView.as_view(),
         name='sponsor-file-create',
         ),
    path("images/<int:pk>",
         view=views.SponsorImageDetailView.as_view(),
         name='sponsor-image-detail',
         ),
    path("images/<int:pk>/update",
         view=views.SponsorImageUpdateView.as_view(),
         name='sponsor-image-update',
         ),
    path("images/<int:pk>/delete",
         view=views.SponsorImageDeleteView.as_view(),
         name='sponsor-image-delete',
         ),
    path("files/<int:pk>",
         view=views.SponsorFileDetailView.as_view(),
         name='sponsor-file-detail',
         ),
    path("files/<int:pk>/update",
         view=views.SponsorFileUpdateView.as_view(),
         name='sponsor-file-update',
         ),
    path("files/<int:pk>/delete",
         view=views.SponsorFileDeleteView.as_view(),
         name='sponsor-file-delete',
         ),
]

example/example/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path

urlpatterns = [
    path('login', auth_views.login, name="login"),
    path('logout', auth_views.logout, name="logout"),
    path('admin/', admin.site.urls, name='admin'),
    path('', include('dj_sponsoring.urls', namespace='dj-sponsoring')),
    path('markdownx/', include('markdownx.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dj_sponsoring/models.py
# coding=utf-8
"""."""

import os

from django.db import models
from django.utils.translation import ugettext_lazy as _

from markdownx.models import MarkdownxField
from markdownx.utils import markdownify

from .storage import OverwriteStorage


def sponsors_upload_to(instance, filename):
    """Callback to create the path where to store the files.

    If the file instance is a Sponsor, the file has to be the logo so it will be uploaded to
        MEDIA_ROOT/sponsors/<sponsor_name>/logo<ext>.
    If the file instance is a SponsorImage, the file has to be an image so it will be uploaded to
        MEDIA_ROOT/sponsors/<sponsor_name>/images/<filename>.
    If the file instance is a SponsorFile, the file has to be a file so it will be uploaded to
        MEDIA_ROOT/sponsors/<sponsor_name>/files/<filename>.
    """
    path = None
    if isinstance(instance, Sponsor):
        basename, ext = os.path.splitext(filename)
        path = os.path.join('sponsors', instance.name, 'logo{}'.format(ext))
    elif isinstance(instance, SponsorImage):
        path = os.path.join('sponsors', instance.sponsor.name, 'images', filename)
    elif isinstance(instance, SponsorFile):
        path = os.path.join('sponsors', instance.sponsor.name, 'files', filename)

    return path


class Sponsor(models.Model):
    """Sponsor entry class handler."""

    name = models.CharField(_('Sponsor name'), max_length=128)
    summary = models.CharField(_('Sponsor summary'), max_length=512)
    description = MarkdownxField(_('Sponsor description'))
    logo = models.ImageField(_('Sponsor logo'), storage=OverwriteStorage(), upload_to=sponsors_upload_to)
    url = models.URLField(_('Sponsor url'))
    created = models.DateTimeField('Sponsor creation date', auto_now_add=True)
    modified = models.DateTimeField('Sponsor last modification date', auto_now=True)

    def __str__(self):
        """Get name of the object."""
        return self.name

    class Meta:
        """Meta class."""

        verbose_name = _("sponsor")
        verbose_name_plural = _("sponsors")
        ordering = ("name", "-modified", "-created")

    def description_md(self):
        """Return the description text mardownified."""
        return markdownify(self.description)


class SponsorImage(models.Model):
    """Sponsor image class handler."""

    sponsor = models.ForeignKey('Sponsor', on_delete=models.CASCADE)
    img = models.ImageField(_('Sponsor image'), upload_to=sponsors_upload_to)
    alt = models.CharField(_('Sponsor image alternative text'), max_length=128)
    description = models.TextField(_('Sponsor image description text'), max_length=512, blank=True)
    created = models.DateTimeField('Sponsor image creation date', auto_now_add=True)
    modified = models.DateTimeField('Sponsor image last modification date', auto_now=True)

    def __str__(self):
        """Get name of the object."""
        return "{} - {}".format(self.sponsor.name, self.alt)

    class Meta:
        """Meta class."""

        verbose_name = _("sponsor image")
        verbose_name_plural = _("sponsor images")
        ordering = ("sponsor", "created")


class SponsorFile(models.Model):
    """Sponsor file class handler."""

    sponsor = models.ForeignKey('Sponsor', on_delete=models.CASCADE)
    file = models.FileField(_('Sponsor file'), upload_to=sponsors_upload_to)
    name = models.CharField(_('Sponsor file name'), max_length=128)
    description = models.CharField(_('Sponsor file small description'), max_length=128)
    created = models.DateTimeField('Sponsor file creation date', auto_now_add=True)
    modified = models.DateTimeField('Sponsor file last modification date', auto_now=True)

    def __str__(self):
        """Get name of the object."""
        return "{} - {}".format(self.sponsor.name, self.name)

    class Meta:
        """Meta class."""

        verbose_name = _("sponsor file")
        verbose_name_plural = _("sponsor files")
        ordering = ("sponsor", "name", "created")

dj_sponsoring/views.py
# coding=utf-8

"""Views."""

from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from .models import (
    Sponsor,
    SponsorFile,
    SponsorImage,
)


class SponsorListView(ListView):
    """View that returns the list of sponsors."""

    model = Sponsor
    paginate_by = 10


class SponsorDetailView(DetailView):
    """Show the details of a sponsor."""

    model = Sponsor


class SponsorCreateView(PermissionRequiredMixin, CreateView):
    """Create a sponsor."""

    model = Sponsor
    fields = '__all__'
    permission_required = 'dj_sponsoring.add_sponsor'

    def get_success_url(self):
        """Get the URL after the success."""
        return reverse('dj_sponsoring:sponsor-detail', kwargs={'pk': self.object.id})


class SponsorUpdateView(PermissionRequiredMixin, UpdateView):
    """Update a sponsor."""

    model = Sponsor
    fields = '__all__'
    permission_required = 'dj_sponsoring.change_sponsor'

    def get_success_url(self):
        """Get the URL after the success."""
        return reverse('dj_sponsoring:sponsor-detail', kwargs={'pk': self.object.id})


class SponsorDeleteView(PermissionRequiredMixin, DeleteView):
    """View that allows the deletion of a sponsor."""

    model = Sponsor
    permission_required = 'dj_sponsoring.delete_sponsor'

    def get_success_url(self, **kwargs):
        """Get the URL after the success."""
        return reverse('dj_sponsoring:sponsors-list')


class SponsorImageListView(ListView):
    """List the images."""

    model = SponsorImage
    paginate_by = 10

    def get_context_data(self, **kwargs):
        """."""
        context = super().get_context_data(**kwargs)
        context['sponsor'] = Sponsor.objects.get(id=self.kwargs['pk'])
        return context

    def get_queryset(self, *args, **kwargs):
        """."""
        qs = SponsorImage.objects.all()
        if 'pk' in self.kwargs:
            qs = SponsorImage.objects.filter(sponsor__id=self.kwargs['pk'])
        return qs


class SponsorImageDetailView(DetailView):
    """Show the detail of an image."""

    model = SponsorImage

    def get_context_data(self, **kwargs):
        """."""
        context = super().get_context_data(**kwargs)
        return context


class SponsorImageCreateView(PermissionRequiredMixin, CreateView):
    """SponsorImageCreateView."""

    model = SponsorImage
    fields = ['alt', 'description', 'img']
    permission_required = 'dj_sponsoring.add_sponsorimage'

    def get_context_data(self, **kwargs):
        """."""
        context = super().get_context_data(**kwargs)
        context['sponsor'] = Sponsor.objects.get(id=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        """Validate the form."""
        form.instance.sponsor = Sponsor.objects.get(id=self.kwargs['pk'])
        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        """Get the URL after the success."""
        return reverse('dj_sponsoring:sponsor-image-detail', kwargs={'pk': self.object.id})


class SponsorImageUpdateView(PermissionRequiredMixin, UpdateView):
    """SponsorImageUpdateView."""

    model = SponsorImage
    fields = ['alt', 'description', 'img']
    permission_required = 'dj_sponsoring.change_sponsorimage'

    def form_valid(self, form):
        """Validate the form."""
        form.instance.sponsor = Sponsor.objects.get(id=self.kwargs['pk'])
        return super().form_valid(form)

    def get_success_url(self):
        """Get the URL after the success."""
        return reverse('dj_sponsoring:sponsor-image-detail', kwargs={'pk': self.object.id})


class SponsorImageDeleteView(PermissionRequiredMixin, DeleteView):
    """SponsorImageDeleteView."""

    model = SponsorImage
    permission_required = 'dj_sponsoring.delete_sponsorimage'

    def get_success_url(self):
        """Get the URL after the success."""
        return reverse('dj_sponsoring:sponsor-images-list', kwargs={'pk': self.kwargs['pk']})


class SponsorFileListView(ListView):
    """SponsorFileListView."""

    model = SponsorFile
    paginate_by = 10

    def get_context_data(self, **kwargs):
        """."""
        context = super().get_context_data(**kwargs)
        context['sponsor'] = Sponsor.objects.get(id=self.kwargs['pk'])
        return context

    def get_queryset(self, *args, **kwargs):
        """."""
        qs = SponsorFile.objects.all()
        if 'pk' in self.kwargs:
            qs = SponsorFile.objects.filter(sponsor__id=self.kwargs['pk'])
        return qs


class SponsorFileDetailView(DetailView):
    """SponsorFileDetailView."""

    model = SponsorFile


class SponsorFileCreateView(PermissionRequiredMixin, CreateView):
    """SponsorFileCreateView."""

    model = SponsorFile
    fields = ['name', 'description', 'file']
    permission_required = 'dj_sponsoring.add_sponsorfile'

    def get_context_data(self, **kwargs):
        """."""
        context = super().get_context_data(**kwargs)
        context['sponsor'] = Sponsor.objects.get(id=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        """Validate the form."""
        form.instance.sponsor = Sponsor.objects.get(id=self.kwargs['pk'])
        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        """Get the URL after the success."""
        return reverse('dj_sponsoring:sponsor-file-detail', kwargs={'pk': self.object.id})


class SponsorFileUpdateView(PermissionRequiredMixin, UpdateView):
    """SponsorFileUpdateView."""

    model = SponsorFile
    fields = ['name', 'description', 'file']
    permission_required = 'dj_sponsoring.change_sponsorfile'

    def get_success_url(self):
        """Get the URL after the success."""
        return reverse('dj_sponsoring:sponsor-file-detail', kwargs={'pk': self.object.id})


class SponsorFileDeleteView(PermissionRequiredMixin, DeleteView):
    """SponsorFileDeleteView."""

    model = SponsorFile
    permission_required = 'dj_sponsoring.delete_sponsorfile'

    def get_success_url(self):
        """Get the URL after the success."""
        return reverse('dj_sponsoring:sponsor-files-list', kwargs={'pk': self.kwargs['pk']})

example/templates/dj_sponsoring/sponsor_confirm_delete.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block path %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'dj_sponsoring:sponsors-list' %}">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ sponsor }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Deletion</a></li>
    </ol>
  </nav>
{% endblock %}

{% block page_title %}
  {{ sponsor }} deletion
{% endblock %}

{% block content %}
<form method="post">
  {% csrf_token %}
  <p>Voulez-vous vraiment supprimer le sponsor "{{ sponsor }}"?</p>
  {% bootstrap_button "Confirmer" button_type="submit" button_class="btn-primary" %}
</form>
{% endblock %}

example/templates/dj_sponsoring/sponsor_detail.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block path %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'dj_sponsoring:sponsors-list' %}">Sponsors list</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ sponsor }}</a></li>
    </ol>
  </nav>
{% endblock %}

{% block page_title_buttons %}
  <div class="btn-group float-right" role="group">
    <a href="{% url 'dj-sponsoring:sponsor-image-create' sponsor.id %}" class="btn btn-primary btn-sm">Add image</a>
    <a href="{% url 'dj-sponsoring:sponsor-file-create' sponsor.id %}" class="btn btn-primary btn-sm">Add file</a>
    <a href="{% url 'dj-sponsoring:sponsor-update' sponsor.id %}" class="btn btn-primary btn-sm">Update</a>
    <a href="{% url 'dj-sponsoring:sponsor-delete' sponsor.id %}" class="btn btn-danger btn-sm">Delete</a>
  </div>
{% endblock %}
  
{% block page_title %}
  {{ sponsor }} <a href="{{ sponsor.url }}" class="badge badge-info">Link</a>
{% endblock %}


{% block content %}
  {% if sponsor.logo %}
    <img class="d-block w-25 float-left mr-2 mb-2" src="{{ sponsor.logo.url }}" alt="{{ sponsor.name }}'s logo">
    <em>{{ sponsor.summary }}</em>
    <p>{{ sponsor.description_md|safe }}</p>
  {% else %}
    <p>{{ sponsor.summary }}</p>
    <p>{{ sponsor.description_md|safe }}</p>
  {% endif %}

  {% if sponsor.sponsorimage_set.count > 0 %}
  <div class="align-items-center">
    <div id="carouselSponsorImageIndicators" class="carousel slide w-100 mt-2 mx-auto" data-ride="carousel">
      <ol class="carousel-indicators">
        {% for i in sponsor.sponsorimage_set.all %}
          <li data-target="#carouselSponsorImageIndicators" data-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}></li>
        {% endfor %}
      </ol>
      <div class="carousel-inner">
        {% for i in sponsor.sponsorimage_set.all %}
          <div class="carousel-item {% if forloop.first %}active{% endif %}">
            <img class="d-block w-100" src="{{ i.img.url }}" alt="{{ i.alt }}">
            <div class="carousel-caption d-none d-md-block">
              <h5>{{ i.alt }}</h5>
              <p>{{ i.description }}</p>
            </div>
          </div>
        {% endfor %}
      </div>
      <a class="carousel-control-prev" href="#carouselSponsorImageIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselSponsorImageIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
  {% endif %}
{% endblock %}

example/templates/dj_sponsoring/sponsor_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form layout="horizontal" %}
    {{ form.media }}
    {% bootstrap_button "Save" button_type="submit" button_class="btn-primary btn-sm" %}
  </form>
{% endblock %}

example/templates/dj_sponsoring/sponsor_list.html
{% extends "base.html" %}
{% load bootstrap4 %}


{% block path %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active">Sponsors list</li>
    </ol>
  </nav>
{% endblock %}

{% block page_title_buttons %}
  <div class="btn-group float-right" role="group">
    <a href="{% url 'dj-sponsoring:sponsor-create' %}" class="btn btn-primary btn-sm">Add sponsor</a>
  </div>
{% endblock %}
  
{% block page_title %}
  Sponsors list
{% endblock %}


{% block content %}
  {% for s in sponsor_list %}
    {% if forloop.first %}
      <div class="list-group">
    {% endif %}

    <a href="{% url 'dj-sponsoring:sponsor-detail' s.id %}" class="list-group-item list-group-item-action flex-column align-items-start">
      <div class="d-flex row">
        <img class="col-md-2" class="mr-2" src="{{ s.logo.url }}" alt="{{ s }}">
        <div class="col-md-10 align-self-center">
          <h5 class="mb-1">{{ s }}</h5>
          <p class="mb-1">{{ s.summary }}</p>
        </div>
      </div>
    </a>

    {% if forloop.last %}
      </div>
    {% endif %}
  {% empty %}
    <p>No sponsors...</p>
    <p>You can create one <a href="{% url 'dj-sponsoring:sponsor-create' %}">here</a></p>
  {% endfor %}

  {% if is_paginated %}
    <nav aria-label="dj-sponsoring-sponsor-detail-pagination">
      <ul class="pagination justify-content-center mt-2">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
        {% endif %}

        {% for i in paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="page-item active">
              <span class="page-link">
                {{ i }}
                <span class="sr-only">(current)</span>
              </span>
            </li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        {% endif %}
      </ul>
    </nav>
  {% endif %}
{% endblock %}

example/templates/dj_sponsoring/sponsorfile_detail.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block path %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'dj_sponsoring:sponsors-list' %}">Sponsors list</a></li>
      <li class="breadcrumb-item"><a href="{% url 'dj_sponsoring:sponsor-detail' sponsorfile.sponsor.id %}">{{ sponsorfile.sponsor }}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'dj_sponsoring:sponsor-files-list' sponsorfile.sponsor.id %}">Files list</a></li>
      <li class="breadcrumb-item active">{{ sponsorfile }}</a></li>
    </ol>
  </nav>
{% endblock %}

{% block page_title_buttons %}
  <div class="btn-group float-right" role="group">
    <a href="{% url 'dj-sponsoring:sponsor-file-update' sponsorfile.id %}" class="btn btn-primary btn-sm">Update</a>
    <a href="{% url 'dj-sponsoring:sponsor-file-delete' sponsorfile.id %}" class="btn btn-danger btn-sm">Delete</a>
  </div>
{% endblock %}

{% block page_title %}
  {{ sponsorfile }}
{% endblock %}

{% block content %}
  <p>Description: {{ sponsorfile.description }}</p>
{% endblock %}

example/templates/dj_sponsoring/sponsorfile_list.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load icons %}
{% load sponsoring %}

{% block path %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'dj_sponsoring:sponsors-list' %}">Sponsors list</a></li>
      <li class="breadcrumb-item"><a href="{% url 'dj_sponsoring:sponsor-detail' sponsor.id %}">{{ sponsor }}</a></li>
      <li class="breadcrumb-item active">Files list</li>
    </ol>
  </nav>
{% endblock %}

{% block page_title %}
  {{ sponsor }}'s files
{% endblock %}

{% block page_title_buttons %}
  <div class="btn-group float-right" role="group">
    <a href="{% url 'dj-sponsoring:sponsor-file-create' sponsor.id %}" class="btn btn-primary btn-sm">Add file</a>
  </div>
{% endblock %}

{% block content %}
  {% for file in sponsorfile_list %}
    {% if forloop.first %}
      <ul class="list-group">
    {% endif %}

    <li class="list-group-item">
      <div class="btn-group float-right" role="group">
        <a href="{% url 'dj-sponsoring:sponsor-file-update' file.id %}" class="btn btn-primary btn-sm">Update file</a>
        <a href="{% url 'dj-sponsoring:sponsor-file-delete' file.id %}" class="btn btn-danger btn-sm">Delete file</a>
      </div>
      <i class="fas fa-{{ file.file|get_icon_extension }}"></i>
      {{ file.name }} ({{ file.file|filename }})<br/>
      {{ file.description }}
    </li>

    {% if forloop.last %}
      </div>
    {% endif %}
  {% empty %}
    <p>No files linked to this sponsor...</p>
    <p>You can create one <a href="{% url 'dj-sponsoring:sponsor-file-create' sponsor.id %}">here</a></p>
  {% endfor %}
{% endblock %}

example/templates/dj_sponsoring/sponsorimage_confirm_delete.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
<form method="post">
  {% csrf_token %}
  <p>Voulez-vous vraiment supprimer l'image "{{ object }}"?</p>
  {% bootstrap_button "Confirmer" button_type="submit" button_class="btn-primary" %}
</form>
{% endblock %}

example/templates/dj_sponsoring/sponsorimage_detail.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
  <div class="btn-group float-right" role="group">
    <a href="{% url 'dj-sponsoring:sponsor-image-update' object.id %}" class="btn btn-primary btn-sm">Update</a>
    <a href="{% url 'dj-sponsoring:sponsor-image-delete' object.id %}" class="btn btn-danger btn-sm">Delete</a>
  </div>

  <h1>{{ object }}</h1>

  <img class="d-block w-100" src="{{ object.img.url }}" alt="{{ object.alt }}">

  <p>Alternative text: {{ object.alt }}</p>
  <p>Description: {{ object.description }}</p>

{% endblock %}

example/templates/dj_sponsoring/sponsorimage_list.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block path %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'dj_sponsoring:sponsors-list' %}">Sponsors list</a></li>
      <li class="breadcrumb-item"><a href="{% url 'dj_sponsoring:sponsor-detail' sponsor.id %}">{{ sponsor }}</a></li>
      <li class="breadcrumb-item active">Images list</li>
    </ol>
  </nav>
{% endblock %}

{% block page_title %}
  {{ sponsor }}'s images
{% endblock %}

{% block page_title_buttons %}
  <div class="btn-group float-right" role="group">
    <a href="{% url 'dj-sponsoring:sponsor-image-create' sponsor.id %}" class="btn btn-primary btn-sm">Add image</a>
  </div>
{% endblock %}

{% block content %}
  {% for image in sponsorimage_list %}
    {% ifchanged image.sponsor %}
      {% if not forloop.first %}
        </div>
      {% endif %}

      <h2 class=" mt-4">{{ image.sponsor }}</h2>
      <div class="list-group">
    {% endifchanged %}

    <a href="{% url 'dj-sponsoring:sponsor-image-detail' image.id %}" class="list-group-item list-group-item-action flex-column align-items-start">
      <div class="d-flex row">
        <img class="col-md-2" class="mr-2" src="{{ image.img.url }}" alt="{{ i.alt }}">
        <div class="col-md-10 align-self-center">
          <h5 class="mb-1">{{ image.alt }}</h5>
          <p class="mb-1">{{ image.description }}</p>
        </div>
      </div>
    </a>

    {% if forloop.last %}
      </div>
    {% endif %}
  {% empty %}
    <p>No images linked to this sponsor...</p>
    <p>You can create one <a href="{% url 'dj-sponsoring:sponsor-image-create' sponsor.id %}">here</a></p>
  {% endfor %}
{% endblock %}